   worker_processes 1;
    error_log stderr;
    user root root;
    events {
        worker_connections  1000;
        reuse_port on;
        multi_accept on;
    }
    worker_rlimit_nofile    20000;
    http {
        access_log /dev/stdout;
        root /var/www/;
        upstream sproxyds {
           least_conn;
           keepalive 40;
           server 127.0.0.1:20000;
        }
        server {
            client_max_body_size 0;
            client_body_timeout 150;
            client_header_timeout 150;
            postpone_output 0;
            client_body_postpone_size 0;
            keepalive_requests 1100;
            keepalive_timeout 300s;
            server_tokens off;
            default_type application/octet-stream;
            gzip off;
            tcp_nodelay on;
            tcp_nopush on;
            sendfile on;
            listen 8181;
            server_name localhost;
            location ~* ^/proxy/(.*)$ {
                rewrite ^/proxy/(.*)$ /$1 last;
            }
            allow all;
            location / {
                proxy_request_buffering off;
                fastcgi_request_buffering off;
                fastcgi_no_cache 1;
                fastcgi_cache_bypass 1;
                fastcgi_buffering off;
                fastcgi_ignore_client_abort on;
                fastcgi_keep_conn on;
                include fastcgi_params;
                fastcgi_pass sproxyds;
                fastcgi_next_upstream error timeout;
            }
        }
    }
