{
 "title": "Replication",
 "tags": [ "Backeat" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "label_values(s3_replication_rpo_seconds_bucket{namespace=\"${namespace}\", job=\"${job_data_processor}\"}, location)"
   },
   {
    "name": "queue_processor",
    "label": "Queue processor",
    "query": "label_values(s3_replication_stage_time_elapsed_bucket{namespace=\"${namespace}\", job=~\"${job_data_processor}|${job_replay_processor}\", location=~\"$location\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Populator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{\n    namespace=\"${namespace}\",\n    job=\"${job_queue_populator}\"\n})"
    }
   ]
  },
  {
   "title": "Data Processor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{\n    namespace=\"${namespace}\",\n    job=\"${job_data_processor}\"\n})"
    }
   ]
  },
  {
   "title": "Replay Processor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{\n    namespace=\"${namespace}\",\n    job=\"${job_replay_processor}\"\n})"
    }
   ]
  },
  {
   "title": "Status Processor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{\n    namespace=\"${namespace}\",\n    job=\"${job_status_processor}\"\n})"
    }
   ]
  },
  {
   "title": "Zookeeper Quorum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(quorum_size{\n    namespace=\"${namespace}\",\n    job=\"${job_zookeeper}\"\n})"
    }
   ]
  },
  {
   "title": "Kafka brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{\n    namespace=\"${namespace}\",\n    job=\"${job_kafka}\"\n})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{\n    namespace=\"${namespace}\",\n    job=\"${job_kafka}\",\n})"
    }
   ]
  },
  {
   "title": "Underreplicated partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(kafka_cluster_partition_underreplicated{\n        namespace=\"${namespace}\",\n        job=\"${job_kafka}\",\n        topic=~\"^(${replication_topic}|${status_topic}|${replay_topic}|${failed_topic})$\",\n    }) by(topic),\n\"topic\", \"$1\", \"topic\", \"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\\\.(?:backbeat-)?(.*)$\")",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Replication Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_write_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Replication Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_bytes_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 / (1 + sum(rate(s3_replication_status_changed_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", replicationStatus=\"FAILED\"}[$__rate_interval]))\n           /\n           sum(rate(s3_replication_status_changed_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", replicationStatus=\"COMPLETED\"}[$__rate_interval]))\n      )\nor vector(100)"
    }
   ]
  },
  {
   "title": "Replays",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_replay_attempts_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(\n  s3_replication_status_changed_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", replicationStatus=\"FAILED\"}[$__rate_interval]\n)) or vector(0)"
    }
   ]
  },
  {
   "title": "Replication backlog size",
   "type": "timeseries",
   "description": "Number of entries which are yet to be processed by replication",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag{\n    namespace=\"${namespace}\",\n    cluster_name=\"${job_kafka}\",\n    topic=~\"${replication_topic}\"\n})"
    }
   ]
  },
  {
   "title": "Avg RPO",
   "type": "stat",
   "description": "RPO is defined as the difference between the time an object was written to and the time when it is picked for replication by the data-processor",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_rpo_seconds_sum{namespace=\"${namespace}\", job=\"${job_data_processor}\"}[$__rate_interval]))\n  /\nsum(rate(s3_replication_rpo_seconds_count{namespace=\"${namespace}\", job=\"${job_data_processor}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg latency",
   "type": "stat",
   "description": "Replication Latency is defined as time taken for an object to replicate successfully to the destination",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_latency_seconds_sum{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval]))\n  /\nsum(rate(s3_replication_latency_seconds_count{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Replication Rate by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_write_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication Speed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_bytes_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication RPO - 99 percentile",
   "type": "timeseries",
   "description": "RPO is defined as the difference between the time an object was written to and the time when it is picked for replication by the data-processor",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n   sum(rate(s3_replication_rpo_seconds_bucket{namespace=\"${namespace}\", job=\"${job_data_processor}\"}[$__rate_interval]))\n   by(le, location))",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication Latency - 99 percentile",
   "type": "timeseries",
   "description": "Replication Latency is defined as time taken for an object to replicate successfully to the destination",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n   sum(rate(s3_replication_latency_seconds_bucket{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval]))\n   by(le, location)\n)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  { "title": "Queue Populator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Replication populator lag",
   "type": "timeseries",
   "description": "Delay between the time an object is updated and the time itis picked up by Queue Populator.The precision is affected however by Prometheus polling interval,and delays up to this interval are expected.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n   max(mongodb_mongod_replset_oplog_head_timestamp{\n           namespace=\"${namespace}\", job=\"${job_mongod}\"})\n   -\n   min(s3_backbeat_populator_log_timestamp{namespace=\"${namespace}\",\n             job=\"${job_queue_populator}\"}),\n0)"
    }
   ]
  },
  {
   "title": "Kafka injection rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{\n            namespace=\"${namespace}\",\n            job=\"${job_kafka}\",\n            topic=~\"${replication_topic}\"\n         }[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Queued objects count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(s3_replication_populator_objects_total{namespace=\"${namespace}\", job=\"${job_queue_populator}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Queued objects size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(s3_replication_populator_bytes_total{namespace=\"${namespace}\", job=\"${job_queue_populator}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Queued objects count/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_populator_objects_total{namespace=\"${namespace}\", job=\"${job_queue_populator}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Queued object size/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_populator_bytes_total{namespace=\"${namespace}\", job=\"${job_queue_populator}\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Queue Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Data processor lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    max(kafka_consumergroup_group_lag{\n        namespace=\"${namespace}\",\n        cluster_name=\"${job_kafka}\",\n        topic=~\"${replication_topic}\",\n        group=~\"${queue_processor_group}($location)$\",\n    }) by(group),\n\"group\", \"$1\", \"group\", \"${queue_processor_group}(.*)$\")",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Data processor throttling",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(s3_circuit_breaker{namespace=\"${namespace}\",job=\"${job_data_processor}\"})*10"
    }
   ]
  },
  {
   "title": "Replay processor lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    max(kafka_consumergroup_group_lag{\n        namespace=\"${namespace}\",\n        cluster_name=\"${job_kafka}\",\n        topic=~\"${replay_topic}\",\n        group=~\"${queue_processor_group}($location)$\",\n    }) by(group),\n\"group\", \"$1\", \"group\", \"${queue_processor_group}(.*)$\")",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Replay processor throttling",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(s3_circuit_breaker{namespace=\"${namespace}\",job=\"${job_replay_processor}\"})*10"
    }
   ]
  },
  {
   "title": "Replication read rate by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_read_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication write rate by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_write_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication read speed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_source_data_bytes_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication write speed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_data_bytes_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication metadata write speed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_metadata_bytes_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication completed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_metadata_status_changed_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStatus=\"COMPLETED\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Distribution by location",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_metadata_status_changed_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replication failed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_metadata_status_changed_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStatus=\"FAILED\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Distribution of errors",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_metadata_status_changed_total{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStatus=\"FAILED\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Time in read stage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(\n  s3_replication_stage_time_elapsed_bucket{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationSourceDataRead\"}[$__rate_interval]\n)) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time in data write stage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(\n  s3_replication_stage_time_elapsed_bucket{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationDataWrite\"}[$__rate_interval]\n)) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time in metadata write stage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(\n  s3_replication_stage_time_elapsed_bucket{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationMetadataWrite\"}[$__rate_interval]\n)) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg read stage duration",
   "type": "stat",
   "description": "Replication Latency is defined as time taken for an object to replicate successfully to the destination",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_stage_time_elapsed_sum{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationSourceDataRead\"}[$__rate_interval]))\n  /\nsum(rate(s3_replication_stage_time_elapsed_count{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationSourceDataRead\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg data write stage duration",
   "type": "stat",
   "description": "Replication Latency is defined as time taken for an object to replicate successfully to the destination",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_stage_time_elapsed_sum{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationDataWrite\"}[$__rate_interval]))\n  /\nsum(rate(s3_replication_stage_time_elapsed_count{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationDataWrite\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg metadata write stage duration",
   "type": "stat",
   "description": "Replication Latency is defined as time taken for an object to replicate successfully to the destination",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_stage_time_elapsed_sum{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationMetadataWrite\"}[$__rate_interval]))\n  /\nsum(rate(s3_replication_stage_time_elapsed_count{namespace=\"${namespace}\", job=~\"$queue_processor\", location=~\"$location\", replicationStage=\"ReplicationDestinationMetadataWrite\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Replay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Replay rate by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_replay_attempts_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\", replayCount=\"1\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replay attempts by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_replay_attempts_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replay success by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_replay_success_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replay failed by location",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_replay_objects_completed_total{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\", replayCount!=\"0\", replicationStatus=\"FAILED\"}[$__rate_interval])) by(location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Replay count distribution",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "label_replace(  sum(increase(\n    s3_replication_replay_count_bucket{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\"}[$__rate_interval]\n  )) by(le),\n\"le\", \"Failed\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Replay distribution by size",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(increase(\n  s3_replication_replay_file_sizes_completed_bucket{namespace=\"${namespace}\", job=\"${job_status_processor}\", location=~\"$location\", replayCount!=\"0\"}[$__rate_interval]\n)) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Status Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Status processor lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag{\n    namespace=\"${namespace}\",\n    cluster_name=\"${job_kafka}\",\n    topic=~\"${status_topic}\"\n})"
    }
   ]
  },
  {
   "title": "Status processor ops rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_status_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_replication_status_process_duration_seconds_sum{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval])) by(result)\n  /\nsum(rate(s3_replication_status_process_duration_seconds_count{namespace=\"${namespace}\", job=\"${job_status_processor}\"}[$__rate_interval])) by(result)",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}