services:
  sproxyd:
    profiles: ['s3c']
    build:
      context: ../sproxyd
    user: 0:0
    privileged: true
    healthcheck:
      test: curl http://localhost:8181 || exit 1
      interval: 10s
      timeout: 30s
      retries: 12
      start_period: 10s
  metadata:
    profiles: ['s3c']
    image: ${METADATA_IMAGE}
    depends_on:
      - sproxyd
    ports:
      - 9000:9000
    environment:
      SPROXYD: sproxyd:8181
    volumes:
        - ./metadata-config.json:/mnt/standalone_workdir/config.json:ro
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9000 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 12
      start_period: 10s
  cloudserver:
    profiles: ['s3c']
    build:
      context: ../cloudserver
    depends_on:
      - metadata
    ports:
      - 8000:8000
    environment:
      S3DATA: file
      S3METADATA: scality
      S3VAULT: mem
      S3_CONFIG_FILE: /conf/config.json
      REMOTE_MANAGEMENT_DISABLE: 1
    command: yarn start
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 12
      start_period: 10s
  redis:
    profiles: ['s3c']
    image: ${REDIS_IMAGE}
    ports:
      - 6379:6379
  kafka:
    profiles: ['s3c']
    image: ${KAFKA_IMAGE}
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      ADVERTISED_HOST: "localhost"
      ADVERTISED_PORT: 9092
