{
 "title": "Cold Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cold Storage Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Archive lag",
   "type": "timeseries",
   "description": "Cold storage archive lag per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-archive-req.+\"})",
     "legendFormat": "{{topic}} {{consumer_id}}"
    }
   ]
  },
  {
   "title": "Restore lag",
   "type": "timeseries",
   "description": "Cold storage restore topic lag per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-restore-req.+\"})",
     "legendFormat": "{{topic}} {{consumer_id}}"
    }
   ]
  },
  {
   "title": "GC lag",
   "type": "timeseries",
   "description": "Cold storage gc lag per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-gc-req.+\"})",
     "legendFormat": "{{topic}} {{consumer_id}}"
    }
   ]
  },
  {
   "title": "Status lag",
   "type": "timeseries",
   "description": "Cold storage status lag per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-status.+\"})",
     "legendFormat": "{{topic}} {{consumer_id}}"
    }
   ]
  },
  {
   "title": "Dead letter lag",
   "type": "timeseries",
   "description": "Cold storage dead letter lag per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-dead-letter.+\"})"
    }
   ]
  },
  { "title": "Cold Storage Offset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Archive offset",
   "type": "timeseries",
   "description": "Cold storage archive topic offset per location per consumer group",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_offset{topic=~\".+cold-archive-req.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Restore offset",
   "type": "timeseries",
   "description": "Cold storage restore topic offset per topic per consumer group",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_offset{topic=~\".+cold-restore-req.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "GC offset",
   "type": "timeseries",
   "description": "Cold storage gc topic offset per topic per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_offset{topic=~\".+cold-gc-req.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Status offset",
   "type": "timeseries",
   "description": "Cold storage status topic offset per location per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_lag{topic=~\".+cold-status.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Dead letter offset",
   "type": "timeseries",
   "description": "Cold storage dead letter topic offset per location per consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(topic, consumer_id)(kafka_consumergroup_group_offset{topic=~\".+cold-dead-letter.+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}