{
 "title": "OOB Ingestion Global",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "populatorJob", "label": "populatorJob", "query": "${POPULATOR_JOB}" },
   { "name": "processorJob", "label": "processorJob", "query": "${PROCESSOR_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Producer",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${populatorJob}\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "count(up{job=~\"${populatorJob}\"})-sum(up{job=~\"${populatorJob}\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Ingestion Processor",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${processorJob}\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "count(up{job=~\"${processorJob}\"})-sum(up{job=~\"${processorJob}\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Objects ingested",
   "type": "graph",
   "description": "How many objects we are ingesting per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Obj/s", "label": "Objects per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zenko_ingestion_mongo_processed_elapsed_seconds_bucket[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Ingestion Success Rate",
   "type": "graph",
   "description": "What ratio of ingestion for success and failures",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zenko_ingestion_mongo_processed_elapsed_seconds_bucket{status=\"success\"}[$__rate_interval]))/sum(rate(zenko_ingestion_mongo_processed_elapsed_seconds_bucket[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Ingestion Backlog",
   "type": "graph",
   "description": "How many objects we are waiting to ingest",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "entries" }
   ],
   "targets": [
    {
     "expr": "sum(metadata_journal_size)-sum(ingestion_read_offset)+count(ingestion_read_offset)",
     "legendFormat": "ingestion"
    }
   ]
  }
 ]
}