{
 "title": "OOB Ingestion Global",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job_ingestion_producer", "label": "job_ingestion_producer", "query": "${job_ingestion_producer}" },
   { "name": "job_ingestion_processor", "label": "job_ingestion_processor", "query": "${job_ingestion_processor}" }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Producer",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/1" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${job_ingestion_producer}\", namespace=\"${namespace}\"})",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Ingestion Processor",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/${replicas}" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${job_ingestion_processor}\", namespace=\"${namespace}\"})",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Zookeeper Quorum",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/${stateful_replicas}" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${job_zookeeper}\",namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "stat",
   "description": "How many instances are currently online and offline",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/${stateful_replicas}" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"${namespace}\", job=\"${job_kafka}\"})"
    }
   ]
  },
  {
   "title": "Objects ingested",
   "type": "graph",
   "description": "How many objects we are ingesting per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Obj/s", "label": "Objects per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_ingestion_mongo_processed_elapsed_seconds_bucket{job=\"${job_ingestion_processor}\", namespace=\"${namespace}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Ingestion Success Rate",
   "type": "graph",
   "description": "What ratio of ingestion for success and failures",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "Success rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_ingestion_mongo_processed_elapsed_seconds_bucket{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\", status=\"success\"}[$__rate_interval]))/sum(rate(s3_ingestion_mongo_processed_elapsed_seconds_bucket{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Ingestion Backlog",
   "type": "graph",
   "description": "How many objects we are waiting to ingest",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "entries" }
   ],
   "targets": [
    {
     "expr": "sum(s3_ingestion_metadata_journal_size{job=\"${job_ingestion_producer}\", namespace=\"${namespace}\"})-sum(s3_ingestion_read_offset{job=\"${job_ingestion_producer}\", namespace=\"${namespace}\"})+count(s3_ingestion_read_offset{job=\"${job_ingestion_producer}\", namespace=\"${namespace}\"})",
     "legendFormat": "ingestion"
    }
   ]
  }
 ]
}