{
 "title": "OOB Ingestion Processor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "${namespace}" },
   { "name": "job_ingestion_processor", "label": "job_ingestion_processor", "query": "${job_ingestion_processor}" },
   { "name": "replicas", "label": "replicas", "query": "${replicas}" }
  ]
 },
 "panels": [
  {
   "title": "Recent Status",
   "type": "timeseries",
   "description": "Recent health status of all ingestion processor pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"})",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "description": "Current health status of all ingestion processor pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/${replicas}" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"})",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Success jobs",
   "type": "timeseries",
   "description": "Number of ingestion processor jobs completed successfully per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ingestion_mongo_processed_elapsed_seconds_count{status=\"success\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval]))",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Error jobs",
   "type": "timeseries",
   "description": "Number of ingestion processor jobs that failed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ingestion_mongo_processed_elapsed_seconds_count{status=\"error\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval]))",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Recent percentage of successful jobs",
   "type": "timeseries",
   "description": "Recent percentage of successful jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ingestion_mongo_processed_elapsed_seconds_count{status=\"success\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\" }) * 100 / sum(ingestion_mongo_processed_elapsed_seconds_count{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"})",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Current percentage of successful jobs",
   "type": "gauge",
   "description": "Current percentage of successful jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ingestion_mongo_processed_elapsed_seconds_count{status=\"success\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\" }) * 100 / sum(ingestion_mongo_processed_elapsed_seconds_count{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"})",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Jobs latency",
   "type": "timeseries",
   "description": "How long does it take for successful ingestion processor job to complete.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ingestion_mongo_processed_elapsed_seconds_sum{status=\"success\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval])) / sum(rate(ingestion_mongo_processed_elapsed_seconds_count{status=\"success\", namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval]))",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  },
  {
   "title": "Kafka entries pulled for ingestion",
   "type": "timeseries",
   "description": "Number of Kafka entries pulled by the ingestion processor per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(ingestion_kafka_message_pulled_total{namespace=\"${namespace}\", job=\"${job_ingestion_processor}\"}[$__rate_interval]))",
     "legendFormat": "Ingestion processor(s)"
    }
   ]
  }
 ]
}