{
 "title": "OOB Ingestion Populator",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "${VAR_JOB}" },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recent Status",
   "type": "graph",
   "description": "Recent status for ingestion populators.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Active Services" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"${job}\", namespace=~\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "description": "Current online or offline status of all ingestion populator pods",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\"${job}\", namespace=~\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Objects queued",
   "type": "graph",
   "description": "How many objects are being queued by the ingestion populator.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Objects per second" }
   ],
   "targets": [
    {
     "expr": "sum by (locationNameRaftID, pod) (rate(ingestion_objects_queued_total[$__rate_interval]))",
     "legendFormat": "Location and raft ID '{{locationNameRaftID}}' in '{{pod}}'"
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ingestion populator metadata journal lag",
   "type": "graph",
   "description": "How far the ingestion populator is behind in the raft journal.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Lag" }
   ],
   "targets": [
    {
     "expr": "metadata_journal_size-ingestion_read_offset+1",
     "legendFormat": "Location and raft ID '{{locationNameRaftID}}' in '{{pod}}'"
    }
   ]
  },
  {
   "title": "Metadata journal entries processed",
   "type": "graph",
   "description": "How many raft journal entries have been processed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Entries per second" }
   ],
   "targets": [
    {
     "expr": "sum by (locationNameRaftID, pod) (rate(ingestion_journal_entries_processed_total[$__rate_interval]))",
     "legendFormat": "Location and raft ID '{{locationNameRaftID}}' in '{{pod}}'"
    }
   ]
  }
 ]
}