---
apiVersion: v1
kind: Pod
metadata:
  name: "backbeat-test-pod"
spec:
  containers:
  - name: aggressor
    image: "{{ images.aggressor }}"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "3"
        memory: 3Gi
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  - name: mongo
    image: scality/ci-mongo:3.6.8
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 512Mi
  - name: kafka
    image: "{{ images.kafka }}"
    resources:
      requests:
        cpu: "250m"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
  - name: redis
    image: redis:alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
  volumes:
    - name: workspace
      emptyDir: {}
