---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: docker
      path: eve/workers/unit_and_feature_tests
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: Npm install
          command: npm install --unsafe-perm
      - ShellCommand:
          name: run static analysis tools on markdown
          command: npm run --silent lint_md
      - ShellCommand:
          name: run static analysis tools on code
          command: npm run --silent lint
      - ShellCommand:
          name: run unit tests
          command: npm test
      # - ShellCommand:
      #     name: run server api functional tests
      #     command: TEST_SWITCH=1 npm start && bash tests/utils/wait_for_local_port.bash 8900 40 && npm run ft_server_test
      - ShellCommand:
          name: run s3 server and run feature tests
          command: bash ./eve/workers/unit_and_feature_tests/run_server_tests.bash
          workdir: '%(prop:builddir)s/build'
      # - ShellCommand:
      #     name: run feature tests
      #     command: TEST_SWITCH=1 npm run ft_test
